version: "3.9"

services:
  sentiment-api:
    build: .
    container_name: sentiment-analyzer
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
